import { storiesOf } from '@storybook/react'
import React from 'react'
import { Provider } from 'react-redux'

import FirmwareReleaseNotes from '.'

import { configureStore } from 'state/store'

const mockedStore = {
  devices: {
    isFetching: false,
    found: [
      {
        DETAIL: 'detail',
        STATE: 'working',
        STATEDESCR: 'Working',
        SERIAL: 'ZT191585000549A0355',
        MODEL: 'PV Supervisor PVS6',
        HWVER: '6.02',
        SWVER: '2021.3, Build 10063',
        DEVICE_TYPE: 'PVS',
        DATATIME: '2021,03,11,15,37,41',
        dl_err_count: '0',
        dl_comm_err: '0',
        dl_skipped_scans: '0',
        dl_scan_time: '0',
        dl_untransmitted: '2550',
        dl_uptime: '161280',
        dl_cpu_load: '1.14',
        dl_mem_used: '76216',
        dl_flash_avail: '79503',
        panid: 453726776,
        CURTIME: '2021,03,11,15,37,41'
      },
      {
        ISDETAIL: true,
        SERIAL: 'PVS6M19150355p',
        TYPE: 'PVS5-METER-P',
        STATE: 'working',
        STATEDESCR: 'Has Not Reported',
        MODEL: 'PVS6M0400p',
        DESCR: 'Power Meter PVS6M19150355p',
        DEVICE_TYPE: 'Power Meter',
        SWVER: '3000',
        PORT: '',
        CAL0: '50',
        origin: 'data_logger',
        OPERATION: 'noop',
        CURTIME: '2021,03,11,15,37,41'
      },
      {
        ISDETAIL: true,
        SERIAL: 'PVS6M19150355c',
        TYPE: 'PVS5-METER-C',
        STATE: 'working',
        STATEDESCR: 'Has Not Reported',
        MODEL: 'PVS6M0400c',
        DESCR: 'Power Meter PVS6M19150355c',
        DEVICE_TYPE: 'Power Meter',
        SWVER: '3000',
        PORT: '',
        CAL0: '100',
        origin: 'data_logger',
        OPERATION: 'noop',
        CURTIME: '2021,03,11,15,37,41'
      },
      {
        ISDETAIL: true,
        SERIAL: 'E00121939001311',
        TYPE: 'SOLARBRIDGE',
        STATE: 'working',
        STATEDESCR: 'Working',
        MODEL: 'AC_Module_Type_E',
        DESCR: 'Inverter E00121939001311',
        DEVICE_TYPE: 'Another Device 2',
        PANEL: 'SPR-E19-320-E-AC',
        SWVER: '4.14.5',
        PORT: '',
        MOD_SN: '',
        NMPLT_SKU: '',
        DATATIME: '2021,03,11,15,37,41',
        ltea_3phsum_kwh: '0',
        p_3phsum_kw: '0',
        vln_3phavg_v: '0',
        i_3phsum_a: '0',
        p_mppt1_kw: '0.0006',
        v_mppt1_v: '48.21',
        i_mppt1_a: '0.01',
        t_htsnk_degc: '26',
        freq_hz: '0',
        stat_ind: '0',
        origin: 'data_logger',
        OPERATION: 'noop',
        CURTIME: '2021,03,11,15,37,42'
      },
      {
        ISDETAIL: true,
        SERIAL: 'E00121939001311',
        TYPE: 'SOLARBRIDGE',
        STATE: 'working',
        STATEDESCR: 'Working',
        MODEL: 'AC_Module_Type_E',
        DESCR: 'Inverter E00121939001311',
        DEVICE_TYPE: '2 Another Device',
        PANEL: 'SPR-E19-320-E-AC',
        SWVER: '4.14.5',
        PORT: '',
        MOD_SN: '',
        NMPLT_SKU: '',
        DATATIME: '2021,03,11,15,37,41',
        ltea_3phsum_kwh: '0',
        p_3phsum_kw: '0',
        vln_3phavg_v: '0',
        i_3phsum_a: '0',
        p_mppt1_kw: '0.0006',
        v_mppt1_v: '48.21',
        i_mppt1_a: '0.01',
        t_htsnk_degc: '26',
        freq_hz: '0',
        stat_ind: '0',
        origin: 'data_logger',
        OPERATION: 'noop',
        CURTIME: '2021,03,11,15,37,42'
      },
      {
        ISDETAIL: true,
        SERIAL: 'E00121939001311',
        TYPE: 'SOLARBRIDGE',
        STATE: 'working',
        STATEDESCR: 'Working',
        MODEL: 'AC_Module_Type_E',
        DESCR: 'Inverter E00121939001311',
        DEVICE_TYPE: 'Another Device',
        PANEL: 'SPR-E19-320-E-AC',
        SWVER: '4.14.5',
        PORT: '',
        MOD_SN: '',
        NMPLT_SKU: '',
        DATATIME: '2021,03,11,15,37,41',
        ltea_3phsum_kwh: '0',
        p_3phsum_kw: '0',
        vln_3phavg_v: '0',
        i_3phsum_a: '0',
        p_mppt1_kw: '0.0006',
        v_mppt1_v: '48.21',
        i_mppt1_a: '0.01',
        t_htsnk_degc: '26',
        freq_hz: '0',
        stat_ind: '0',
        origin: 'data_logger',
        OPERATION: 'noop',
        CURTIME: '2021,03,11,15,37,42'
      },
      {
        ISDETAIL: true,
        SERIAL: 'E00121939001311',
        TYPE: 'SOLARBRIDGE',
        STATE: 'working',
        STATEDESCR: 'Working',
        MODEL: 'AC_Module_Type_E',
        DESCR: 'Inverter E00121939001311',
        DEVICE_TYPE: 'ESS HUB',
        PANEL: 'SPR-E19-320-E-AC',
        SWVER: '4.14.5',
        PORT: '',
        MOD_SN: '',
        NMPLT_SKU: '',
        DATATIME: '2021,03,11,15,37,41',
        ltea_3phsum_kwh: '0',
        p_3phsum_kw: '0',
        vln_3phavg_v: '0',
        i_3phsum_a: '0',
        p_mppt1_kw: '0.0006',
        v_mppt1_v: '48.21',
        i_mppt1_a: '0.01',
        t_htsnk_degc: '26',
        freq_hz: '0',
        stat_ind: '0',
        origin: 'data_logger',
        OPERATION: 'noop',
        CURTIME: '2021,03,11,15,37,42'
      },
      {
        ISDETAIL: true,
        SERIAL: 'E00121939001311',
        TYPE: 'SOLARBRIDGE',
        STATE: 'working',
        STATEDESCR: 'Working',
        MODEL: 'AC_Module_Type_E',
        DESCR: 'Inverter E00121939001311',
        DEVICE_TYPE: 'Battery',
        PANEL: 'SPR-E19-320-E-AC',
        SWVER: '4.14.5',
        PORT: '',
        MOD_SN: '',
        NMPLT_SKU: '',
        DATATIME: '2021,03,11,15,37,41',
        ltea_3phsum_kwh: '0',
        p_3phsum_kw: '0',
        vln_3phavg_v: '0',
        i_3phsum_a: '0',
        p_mppt1_kw: '0.0006',
        v_mppt1_v: '48.21',
        i_mppt1_a: '0.01',
        t_htsnk_degc: '26',
        freq_hz: '0',
        stat_ind: '0',
        origin: 'data_logger',
        OPERATION: 'noop',
        CURTIME: '2021,03,11,15,37,42'
      },
      {
        ISDETAIL: true,
        SERIAL: 'E00121939001312',
        TYPE: 'SOLARBRIDGE',
        STATE: 'working',
        STATEDESCR: 'Working',
        MODEL: 'AC_Module_Type_E',
        DESCR: 'Inverter E00121939001311',
        DEVICE_TYPE: 'Inverter 2',
        PANEL: 'SPR-E19-320-E-AC',
        SWVER: '4.14.5',
        PORT: '',
        MOD_SN: '',
        NMPLT_SKU: '',
        DATATIME: '2021,03,11,15,37,41',
        ltea_3phsum_kwh: '0',
        p_3phsum_kw: '0',
        vln_3phavg_v: '0',
        i_3phsum_a: '0',
        p_mppt1_kw: '0.0006',
        v_mppt1_v: '48.21',
        i_mppt1_a: '0.01',
        t_htsnk_degc: '26',
        freq_hz: '0',
        stat_ind: '0',
        origin: 'data_logger',
        OPERATION: 'noop',
        CURTIME: '2021,03,11,15,37,42'
      },
      {
        ISDETAIL: true,
        SERIAL: 'E00121939001311',
        TYPE: 'SOLARBRIDGE',
        STATE: 'working',
        STATEDESCR: 'Working',
        MODEL: 'AC_Module_Type_E',
        DESCR: 'Inverter E00121939001311',
        DEVICE_TYPE: 'Inverter',
        PANEL: 'SPR-E19-320-E-AC',
        SWVER: '4.14.5',
        PORT: '',
        MOD_SN: '',
        NMPLT_SKU: '',
        DATATIME: '2021,03,11,15,37,41',
        ltea_3phsum_kwh: '0',
        p_3phsum_kw: '0',
        vln_3phavg_v: '0',
        i_3phsum_a: '0',
        p_mppt1_kw: '0.0006',
        v_mppt1_v: '48.21',
        i_mppt1_a: '0.01',
        t_htsnk_degc: '26',
        freq_hz: '0',
        stat_ind: '0',
        origin: 'data_logger',
        OPERATION: 'noop',
        CURTIME: '2021,03,11,15,37,42'
      },
      {
        ISDETAIL: true,
        SERIAL: 'E00121939002888',
        TYPE: 'SOLARBRIDGE',
        STATE: 'working',
        STATEDESCR: 'Working',
        MODEL: 'AC_Module_Type_E',
        DESCR: 'Inverter E00121939002888',
        DEVICE_TYPE: 'Inverter',
        PANEL: 'SPR-E19-320-E-AC',
        SWVER: '4.14.5',
        PORT: '',
        MOD_SN: '',
        NMPLT_SKU: '',
        DATATIME: '2021,03,11,15,37,41',
        ltea_3phsum_kwh: '0',
        p_3phsum_kw: '0',
        vln_3phavg_v: '0',
        i_3phsum_a: '0',
        p_mppt1_kw: '0.0015',
        v_mppt1_v: '48.17',
        i_mppt1_a: '0.03',
        t_htsnk_degc: '29',
        freq_hz: '0',
        stat_ind: '0',
        origin: 'data_logger',
        OPERATION: 'noop',
        CURTIME: '2021,03,11,15,37,42'
      },
      {
        ISDETAIL: true,
        SERIAL: 'E00121939002888',
        TYPE: 'SOLARBRIDGE',
        STATE: 'working',
        STATEDESCR: 'Working',
        MODEL: 'AC_Module_Type_E',
        DESCR: 'Inverter E00121939002888',
        DEVICE_TYPE: 'ESS superlongname with this will be able to test',
        PANEL: 'SPR-E19-320-E-AC',
        SWVER: '4.14.5',
        PORT: '',
        MOD_SN: '',
        NMPLT_SKU: '',
        DATATIME: '2021,03,11,15,37,41',
        ltea_3phsum_kwh: '0',
        p_3phsum_kw: '0',
        vln_3phavg_v: '0',
        i_3phsum_a: '0',
        p_mppt1_kw: '0.0015',
        v_mppt1_v: '48.17',
        i_mppt1_a: '0.03',
        t_htsnk_degc: '29',
        freq_hz: '0',
        stat_ind: '0',
        origin: 'data_logger',
        OPERATION: 'noop',
        CURTIME: '2021,03,11,15,37,42'
      }
    ],
    progress: {
      progress: [
        {
          TYPE: 'MicroInverters',
          PROGR: '100',
          NFOUND: '0'
        },
        {
          TYPE: 'SPRf',
          PROGR: '100',
          NFOUND: '0'
        },
        {
          TYPE: 'SunSpecDevices',
          PROGR: '100',
          NFOUND: '0'
        },
        {
          TYPE: 'Meters',
          PROGR: '100',
          NFOUND: '0'
        },
        {
          TYPE: 'HubPlus',
          PROGR: '100',
          NFOUND: '0'
        },
        {
          TYPE: 'OtherInverters',
          PROGR: '100',
          NFOUND: '0'
        },
        {
          TYPE: 'MetStations',
          PROGR: '100',
          NFOUND: '0'
        },
        {
          TYPE: 'MIO',
          PROGR: '100',
          NFOUND: '0'
        },
        {
          TYPE: 'PV Disconnect',
          PROGR: '100',
          NFOUND: '0'
        },
        {
          TYPE: 'SPRm',
          PROGR: '100',
          NFOUND: '0'
        },
        {
          TYPE: 'SPRk',
          PROGR: '100',
          NFOUND: '0'
        },
        {
          TYPE: 'SPRp',
          PROGR: '100',
          NFOUND: '0'
        },
        {
          TYPE: 'GroundCurMon',
          PROGR: '100',
          NFOUND: '0'
        },
        {
          TYPE: 'PVS5Meter',
          PROGR: '100',
          NFOUND: '2'
        }
      ],
      complete: true,
      result: 'succeed'
    },
    error: '',
    pushCandidatesError: false,
    isFetchingCandidates: false,
    candidates: [],
    allCandidatesFound: true,
    discoveryComplete: true,
    claimingDevices: false,
    claimProgress: 0,
    claimedDevices: false,
    claimError: '',
    miModels: [],
    fetchingDevices: false,
    _persist: {
      version: -1,
      rehydrated: true
    }
  }
}

storiesOf('Legacy discovery', module).add('Multiple devices', () => {
  const { store } = configureStore(mockedStore)

  return (
    <div className="full-min-height pl-10 pr-10">
      <Provider store={store}>
        <FirmwareReleaseNotes />
      </Provider>
    </div>
  )
})
