import { createAction } from 'redux-act'

export const PVS_FIRMWARE_UPDATE_URL = createAction('PVS_FIRMWARE_UPDATE_URL')
export const PVS_FIRMWARE_DOWNLOAD_INIT = createAction(
  'PVS_FIRMWARE_DOWNLOAD_INIT'
)
export const PVS_FIRMWARE_DOWNLOAD_PROGRESS = createAction(
  'PVS_FIRMWARE_DOWNLOAD_PROGRESS'
)
export const PVS_FIRMWARE_DOWNLOAD_SUCCESS = createAction(
  'PVS_FIRMWARE_DOWNLOAD_SUCCESS'
)
export const PVS_FIRMWARE_DOWNLOAD_ERROR = createAction(
  'PVS_FIRMWARE_DOWNLOAD_ERROR'
)
export const PVS_SET_FILE_INFO = createAction('PVS_SET_FILE_INFO')
export const PVS_DECOMPRESS_LUA_FILES_INIT = createAction(
  'PVS_DECOMPRESS_LUA_FILES_INIT'
)
export const PVS_DECOMPRESS_LUA_FILES_SUCCESS = createAction(
  'PVS_DECOMPRESS_LUA_FILES_SUCCESS'
)
export const PVS_DECOMPRESS_LUA_FILES_ERROR = createAction(
  'PVS_DECOMPRESS_LUA_FILES_ERROR'
)
export const PVS_FIRMWARE_REPORT_SUCCESS = createAction(
  'PVS_FIRMWARE_REPORT_SUCCESS'
)
export const PVS_FIRMWARE_MODAL_IS_CONNECTED = createAction(
  'PVS_FIRMWARE_MODAL_IS_CONNECTED'
)
export const DOWNLOAD_ALLOW_WITH_PVS = createAction('DOWNLOAD_ALLOW_WITH_PVS')
export const SET_ESS_UPDATE_OVERRIDE = createAction(
  'SET_ESS_UPDATE_OVERRIDE_URL'
)
export const SET_PVS_UPDATE_OVERRIDE = createAction(
  'SET_PVS_UPDATE_OVERRIDE_URL'
)
export const DEFAULT_ALL_UPDATE_OVERRIDES = createAction(
  'DEFAULT_ALL_UPDATE_OVERRIDES'
)
export const DOWNLOAD_URLS_UPDATED = createAction('DOWNLOAD_URLS_UPDATED')
export const FILES_VERIFY = createAction('FILES_VERIFY')
export const FILES_VERIFY_FAILED = createAction('FILES_VERIFY_FAILED')
export const FILES_VERIFY_GP_COMPLETED = createAction(
  'FILES_VERIFY_GP_COMPLETED'
)
export const FILES_VERIFY_ESS_COMPLETED = createAction(
  'FILES_VERIFY_ESS_COMPLETED'
)
export const FILES_VERIFY_PVS_COMPLETED = createAction(
  'FILES_VERIFY_PVS_COMPLETED'
)
