import { createAction } from 'redux-act'

export const PVS_FIRMWARE_UPDATE_URL = createAction('PVS_FIRMWARE_UPDATE_URL')
export const PVS_FIRMWARE_DOWNLOAD_INIT = createAction(
  'PVS_FIRMWARE_DOWNLOAD_INIT'
)
export const PVS_FIRMWARE_DOWNLOAD_PROGRESS = createAction(
  'PVS_FIRMWARE_DOWNLOAD_PROGRESS'
)
export const PVS_FIRMWARE_DOWNLOAD_SUCCESS = createAction(
  'PVS_FIRMWARE_DOWNLOAD_SUCCESS'
)
export const PVS_FIRMWARE_DOWNLOAD_ERROR = createAction(
  'PVS_FIRMWARE_DOWNLOAD_ERROR'
)
export const PVS_SET_FILE_INFO = createAction('PVS_SET_FILE_INFO')
export const PVS_DECOMPRESS_LUA_FILES_INIT = createAction(
  'PVS_DECOMPRESS_LUA_FILES_INIT'
)
export const PVS_DECOMPRESS_LUA_FILES_SUCCESS = createAction(
  'PVS_DECOMPRESS_LUA_FILES_SUCCESS'
)
export const PVS_DECOMPRESS_LUA_FILES_ERROR = createAction(
  'PVS_DECOMPRESS_LUA_FILES_ERROR'
)
export const PVS_FIRMWARE_REPORT_SUCCESS = createAction(
  'PVS_FIRMWARE_REPORT_SUCCESS'
)
export const DOWNLOAD_ALLOW_WITH_PVS = createAction('DOWNLOAD_ALLOW_WITH_PVS')
export const SET_ESS_UPDATE_OVERRIDE = createAction(
  'SET_ESS_UPDATE_OVERRIDE_URL'
)
export const SET_PVS_UPDATE_OVERRIDE = createAction(
  'SET_PVS_UPDATE_OVERRIDE_URL'
)
export const DEFAULT_ALL_UPDATE_OVERRIDES = createAction(
  'DEFAULT_ALL_UPDATE_OVERRIDES'
)
export const DOWNLOAD_URLS_UPDATED = createAction('DOWNLOAD_URLS_UPDATED')

// PVS5 FW actions
export const PVS5_FW_DOWNLOAD_INIT = createAction('PVS5_FW_DOWNLOAD_INIT')
export const PVS5_FW_DOWNLOAD_RESTART = createAction('PVS5_FW_DOWNLOAD_RESTART')
export const PVS5_FW_DOWNLOAD_PROGRESS = createAction(
  'PVS5_FW_DOWNLOAD_PROGRESS'
)
export const PVS5_SCRIPTS_DOWNLOAD_PROGRESS = createAction(
  'PVS5_SCRIPTS_DOWNLOAD_PROGRESS'
)
export const PVS5_KERNEL_DOWNLOAD_PROGRESS = createAction(
  'PVS5_KERNEL_DOWNLOAD_PROGRESS'
)
export const PVS5_FW_DOWNLOAD_SUCCESS = createAction('PVS5_FW_DOWNLOAD_SUCCESS')
export const PVS5_SCRIPTS_DOWNLOAD_SUCCESS = createAction(
  'PVS5_SCRIPTS_DOWNLOAD_SUCCESS'
)
export const PVS5_KERNEL_DOWNLOAD_SUCCESS = createAction(
  'PVS5_KERNEL_DOWNLOAD_SUCCESS'
)
export const PVS5_FW_VERIFY_DOWNLOAD = createAction('PVS5_FW_VERIFY_DOWNLOAD')
export const PVS5_SCRIPTS_VERIFY_DOWNLOAD = createAction(
  'PVS5_SCRIPTS_VERIFY_DOWNLOAD'
)
export const PVS5_KERNEL_VERIFY_DOWNLOAD = createAction(
  'PVS5_KERNEL_VERIFY_DOWNLOAD'
)
export const PVS5_FW_DOWNLOAD_ERROR = createAction('PVS5_FW_DOWNLOAD_ERROR')
export const PVS5_SCRIPTS_DOWNLOAD_ERROR = createAction(
  'PVS5_SCRIPTS_DOWNLOAD_ERROR'
)
export const PVS5_KERNEL_DOWNLOAD_ERROR = createAction(
  'PVS5_KERNEL_DOWNLOAD_ERROR'
)
export const PVS5_SET_FW_INFO = createAction('PVS5_SET_FW_INFO')
export const PVS5_DECOMPRESS_LUA_FILES_INIT = createAction(
  'PVS5_DECOMPRESS_LUA_FILES_INIT'
)
export const PVS5_DECOMPRESS_LUA_FILES_SUCCESS = createAction(
  'PVS5_DECOMPRESS_LUA_FILES_SUCCESS'
)
export const SET_DO_NOT_UPDATE_PVS = createAction('SET_DO_NOT_UPDATE_PVS')
export const SET_DO_NOT_UPDATE_ESS = createAction('SET_DO_NOT_UPDATE_ESS')
