import { createAction } from 'redux-act'

export const INIT_FIRMWARE_UPDATE = createAction('INIT_FIRMWARE_UPDATE')
export const SHOW_FIRMWARE_UPDATE_MODAL = createAction(
  'SHOW_FIRMWARE_UPDATE_MODAL'
)
export const RESET_FIRMWARE_UPDATE = createAction('RESET_FIRMWARE_UPDATE')
export const START_FIRMWARE_UPDATE_POLLING = createAction(
  'START_FIRMWARE_UPDATE_POLLING'
)
export const POLL_FIRMWARE_UPDATE = createAction('POLL_FIRMWARE_UPDATE')
export const STOP_FIRMWARE_UPDATE_POLLING = createAction(
  'STOP_FIRMWARE_UPDATE_POLLING'
)
export const WAIT_FOR_NETWORK_AFTER_FIRMWARE_UPDATE = createAction(
  'WAIT_FOR_NETWORK_AFTER_FIRMWARE_UPDATE'
)
export const FIRMWARE_UPDATE_COMPLETE = createAction('FIRMWARE_UPDATE_COMPLETE')
export const FIRMWARE_UPDATE_ERROR = createAction('FIRMWARE_UPDATE_ERROR')
export const FIRMWARE_GET_VERSION_ERROR = createAction(
  'FIRMWARE_GET_VERSION_ERROR'
)
export const NO_FIRMWARE_UPDATE_AVAILABLE = createAction(
  'NO_FIRMWARE_UPDATE_AVAILABLE'
)
export const FIRMWARE_UPDATE_CHECK_FAILURE = createAction(
  'FIRMWARE_UPDATE_CHECK_FAILURE'
)
export const SET_FIRMWARE_RELEASE_NOTES = createAction(
  'SET_FIRMWARE_RELEASE_NOTES'
)
export const GET_RELEASE_NOTES_ERROR = createAction('GET_RELEASE_NOTES_ERROR')
export const FIRMWARE_SET_LAST_SUCCESSFUL_STAGE = createAction(
  'FIRMWARE_SET_LAST_SUCCESSFUL_STAGE'
)

export const INIT_GRID_PROFILE_UPLOAD = createAction('INIT_GRID_PROFILE_UPLOAD')
export const GRID_PROFILE_UPLOAD_COMPLETE = createAction(
  'GRID_PROFILE_UPLOAD_COMPLETE'
)
export const GRID_PROFILE_UPLOAD_ERROR = createAction(
  'GRID_PROFILE_UPLOAD_ERROR'
)
