import { createAction } from 'redux-act'

export const PVS6_GRID_PROFILE_DOWNLOAD_INIT = createAction(
  'PVS6_GRID_PROFILE_DOWNLOAD_INIT'
)
export const PVS6_GRID_PROFILE_DOWNLOAD_PROGRESS = createAction(
  'PVS6_GRID_PROFILE_DOWNLOAD_PROGRESS'
)
export const PVS6_GRID_PROFILE_DOWNLOAD_ERROR = createAction(
  'PVS6_GRID_PROFILE_DOWNLOAD_ERROR'
)
export const PVS6_GRID_PROFILE_DOWNLOAD_SUCCESS = createAction(
  'PVS6_GRID_PROFILE_DOWNLOAD_SUCCESS'
)
export const PVS6_GRID_PROFILE_REPORT_SUCCESS = createAction(
  'PVS6_GRID_PROFILE_REPORT_SUCCESS'
)

export const PVS5_GRID_PROFILE_DOWNLOAD_INIT = createAction(
  'PVS5_GRID_PROFILE_DOWNLOAD_INIT'
)
export const PVS5_GRID_PROFILE_DOWNLOAD_PROGRESS = createAction(
  'PVS5_GRID_PROFILE_DOWNLOAD_PROGRESS'
)
export const PVS5_GRID_PROFILE_DOWNLOAD_ERROR = createAction(
  'PVS5_GRID_PROFILE_DOWNLOAD_ERROR'
)
export const PVS5_GRID_PROFILE_DOWNLOAD_SUCCESS = createAction(
  'PVS5_GRID_PROFILE_DOWNLOAD_SUCCESS'
)
export const PVS5_GRID_PROFILE_REPORT_SUCCESS = createAction(
  'PVS5_GRID_PROFILE_REPORT_SUCCESS'
)
