import { createAction } from 'redux-act'

export const CHECK_LOCATION_PERMISSION_INIT = createAction(
  'CHECK_LOCATION_PERMISSION_INIT'
)
export const CHECK_LOCATION_PERMISSION_SUCCESS = createAction(
  'CHECK_LOCATION_PERMISSION_SUCCESS'
)
export const CHECK_LOCATION_PERMISSION_ERROR = createAction(
  'CHECK_LOCATION_PERMISSION_ERROR'
)

export const REQUEST_LOCATION_PERMISSION_INIT = createAction(
  'REQUEST_LOCATION_PERMISSION_INIT'
)

export const REQUEST_LOCATION_PERMISSION_SUCCESS = createAction(
  'REQUEST_LOCATION_PERMISSION_SUCCESS'
)

export const REQUEST_LOCATION_PERMISSION_ERROR = createAction(
  'REQUEST_LOCATION_PERMISSION_ERROR'
)

export const CHECK_TRACKING_PERMISSION = createAction(
  'CHECK_TRACKING_PERMISSION'
)
export const SET_TRACKING_PERMISSION = createAction('SET_TRACKING_PERMISSION')
export const REQUEST_TRACKING_PERMISSION = createAction(
  'REQUEST_TRACKING_PERMISSION'
)
