import { createAction } from 'redux-act'

export const GET_ESS_STATUS_INIT = createAction('GET_ESS_STATUS_INIT')
export const GET_ESS_STATUS = createAction('GET_ESS_STATUS')
export const GET_ESS_STATUS_SUCCESS = createAction('GET_ESS_STATUS_SUCCESS')
export const GET_ESS_STATUS_ERROR = createAction('GET_ESS_STATUS_ERROR')
export const GET_ESS_STATUS_COMPLETE = createAction('GET_ESS_STATUS_COMPLETE')

export const RUN_EQS_SYSTEMCHECK = createAction('RUN_EQS_SYSTEMCHECK')
export const RUN_EQS_SYSTEMCHECK_SUCCESS = createAction(
  'RUN_EQS_SYSTEMCHECK_SUCCESS'
)

export const GET_PREDISCOVERY = createAction('GET_PREDISCOVERY')
export const GET_PREDISCOVERY_SUCCESS = createAction('GET_PREDISCOVERY_SUCCESS')
export const GET_PREDISCOVERY_ERROR = createAction('GET_PREDISCOVERY_ERROR')
export const GET_PREDISCOVERY_RESET = createAction('GET_PREDISCOVERY_RESET')

export const POST_COMPONENT_MAPPING = createAction('POST_COMPONENT_MAPPING')
export const POST_COMPONENT_MAPPING_SUCCESS = createAction(
  'POST_COMPONENT_MAPPING_SUCCESS'
)
export const POST_COMPONENT_MAPPING_ERROR = createAction(
  'POST_COMPONENT_MAPPING_ERROR'
)

export const GET_COMPONENT_MAPPING_PROGRESS = createAction(
  'GET_COMPONENT_MAPPING_PROGRESS'
)
export const GET_COMPONENT_MAPPING_COMPLETED = createAction(
  'GET_COMPONENT_MAPPING_COMPLETED'
)
export const GET_COMPONENT_MAPPING_ERROR = createAction(
  'GET_COMPONENT_MAPPING_ERROR'
)
export const RESET_COMPONENT_MAPPING = createAction('RESET_COMPONENT_MAPPING')

export const UPLOAD_EQS_FIRMWARE = createAction('UPLOAD_EQS_FIRMWARE')
export const UPLOAD_EQS_FIRMWARE_SUCCESS = createAction(
  'UPLOAD_EQS_FIRMWARE_SUCCESS'
)
export const UPLOAD_EQS_FIRMWARE_ERROR = createAction(
  'UPLOAD_EQS_FIRMWARE_ERROR'
)

export const TRIGGER_EQS_FIRMWARE_SUCCESS = createAction(
  'TRIGGER_EQS_FIRMWARE_SUCCESS'
)
export const TRIGGER_EQS_FIRMWARE_ERROR = createAction(
  'TRIGGER_EQS_FIRMWARE_ERROR'
)

export const UPDATE_EQS_FIRMWARE_SUCCESS = createAction(
  'UPDATE_EQS_FIRMWARE_SUCCESS'
)
export const UPDATE_EQS_FIRMWARE_ERROR = createAction(
  'UPDATE_EQS_FIRMWARE_ERROR'
)

export const UPDATE_EQS_FIRMWARE_PROGRESS = createAction(
  'UPDATE_EQS_FIRMWARE_PROGRESS'
)
export const UPDATE_EQS_FIRMWARE_COMPLETED = createAction(
  'UPDATE_EQS_FIRMWARE_COMPLETED'
)
