import { createAction } from 'redux-act'

export const DOWNLOAD_SUPERUSER_FIRMWARE_LIST = createAction(
  'DOWNLOAD_SUPERUSER_FIRMWARE_LIST'
)
export const DOWNLOAD_ESS_FIRMWARE_LIST_SUCCESS = createAction(
  'DOWNLOAD_ESS_FIRMWARE_LIST_SUCCESS'
)
export const SHOW_SUPERUSER_SETTINGS = createAction('SHOW_SUPERUSER_SETTINGS')
export const HIDE_SUPERUSER_SETTINGS = createAction('HIDE_SUPERUSER_SETTINGS')

export const DOWNLOAD_CM2_FIRMWARE_LIST = createAction(
  'DOWNLOAD_CM2_FIRMWARE_LIST'
)
export const DOWNLOAD_CM2_FIRMWARE_LIST_SUCCESS = createAction(
  'DOWNLOAD_CM2_FIRMWARE_LIST_SUCCESS'
)
export const SET_DO_NOT_UPDATE = createAction('SET_DO_NOT_UPDATE')
